version: '3.7'

services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db

  reservationservice:
    image: reservationservice
    build:
      context: .
      dockerfile: ./ReservationService/Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql/data
      - db-log:/var/opt/mssql/log

volumes:
  db-data:
  db-log: